#!/usr/bin/env python3
"""Build disposable indexes from the reviewed JSONL summary, using stdlib only.

This never edits character cards, sources, grades, scores, or characters.jsonl.
The summary remains subordinate to the character cards and source records.
"""

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import quote


INDEX_NAMES = (
    "master-index.md", "by-archetype.md", "by-visual-hook.md", "by-identity.md",
    "by-desire-mechanism.md", "by-power-method.md", "by-secret-method.md",
    "by-modern-role.md", "by-relationship-mechanism.md", "by-plot-engine.md",
)
CACHE_FIELDS = ("card_id", "name_zh", "tier", "primary_archetype_id")
CARD_ID = re.compile(r"[A-Z0-9]+(?:-[A-Z0-9]+)+-\d+")


def read_utf8(path):
    """Reject invalid UTF-8/BOM, but accept both LF and Windows CRLF."""
    raw = Path(path).read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raise ValueError(f"UTF-8 BOM is not allowed: {path}")
    return raw.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")


def load_library(root):
    schema = json.loads(read_utf8(root / "data/archetypes.json"))
    if not isinstance(schema, dict):
        raise ValueError("data/archetypes.json must be a JSON object")
    records = []
    for number, line in enumerate(read_utf8(root / "data/characters.jsonl").splitlines(), 1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as error:
            raise ValueError(f"characters.jsonl line {number}: {error.msg}") from error
        if not isinstance(record, dict):
            raise ValueError(f"characters.jsonl line {number} must be a JSON object")
        card_id = record.get("card_id")
        if not isinstance(card_id, str) or not CARD_ID.fullmatch(card_id):
            raise ValueError(f"characters.jsonl line {number}: invalid card_id")
        records.append(record)
    if len({record["card_id"] for record in records}) != len(records):
        raise ValueError("Duplicate card_id in characters.jsonl")
    return schema, records


def card_files(root, records):
    """Resolve stable IDs to existing filenames; never invent a card path."""
    paths = {}
    for path in sorted((root / "characters").rglob("*.md")):
        if path.name == "README.md":
            continue
        card_id = path.stem.split("_", 1)[0]
        if not CARD_ID.fullmatch(card_id) or "_" not in path.stem:
            raise ValueError(f"Invalid character filename: {path.relative_to(root)}")
        if card_id in paths:
            raise ValueError(f"More than one character card for {card_id}")
        if not path.resolve().is_relative_to(root.resolve()):
            raise ValueError(f"Character path escapes repository: {path}")
        paths[card_id] = path
    expected = {record["card_id"] for record in records}
    missing, extra = expected - paths.keys(), paths.keys() - expected
    if missing or extra:
        raise ValueError(f"Card/summary IDs differ; missing={sorted(missing)}, unindexed={sorted(extra)}")
    return paths


def character_cache(records):
    # Input order is deliberate: an already-correct cache need not be rewritten.
    return [{field: record[field] for field in CACHE_FIELDS} for record in records]


def cell(value):
    if value is None or value == "":
        return "UNKNOWN"
    return str(value).replace("\\", "\\\\").replace("|", r"\|").replace("\n", "<br>")


def joined(values, separator="；"):
    return cell(separator.join(str(value) for value in values))


def code(value):
    return "`" + cell(value) + "`" if value else "UNKNOWN"


def url_path(path):
    # Keep Chinese filenames readable while escaping Markdown URL delimiters.
    return "".join(quote(char, safe="/-._~") if char in " ()[]#?<>%\\" else char for char in path)


def link(label, path):
    label = cell(label).replace("[", r"\[").replace("]", r"\]")
    return f"[{label}]({url_path(path)})"


def page(title, headers, rows, note=""):
    lines = [
        f"# {title}", "", "<!-- Generated by scripts/build-indexes.py; do not edit by hand. -->", "",
        "> 本页由 [机器摘要](../data/characters.jsonl) 派生。命中后回读人物卡与来源；摘要不作为事实来源。",
    ]
    if note:
        lines.extend(["", note])
    lines.extend(["", "| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)])
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines) + "\n"


def generated_indexes(root, schema, records, paths):
    ordered = sorted(records, key=lambda record: record["card_id"])
    names = {archetype["id"]: archetype["name_zh"] for archetype in schema["archetypes"]}
    usable = [r for r in ordered if r["tier"] in ("Gold", "Silver")]
    mechanisms = [r for r in usable if r["layer_completion"].get("M") is True]
    capsules = [r for r in usable if r["layer_completion"].get("R") is True]
    engines = [r for r in usable if r["layer_completion"].get("P") is True]
    h4_records = [r for r in usable if r["layer_completion"].get("H") is True
                  and r.get("adult_adaptation_age") not in (None, "", "UNKNOWN")]

    def person(record):
        return link(record["name_zh"], "../" + paths[record["card_id"]].relative_to(root).as_posix())

    def capsule(record):
        return (record.get("retrieval_capsule") or {}) if record["layer_completion"].get("R") is True else {}

    def container(record):
        return capsule(record).get("best_urban_container") or {}

    def power(record):
        return capsule(record).get("power_interface") or {}

    def age(record):
        value = record.get("adult_adaptation_age")
        return f"{value}岁" if value not in (None, "", "UNKNOWN") else "UNKNOWN"

    def neighbor(record):
        card_id = record.get("nearest_neighbor_card_id")
        if card_id in paths:
            return link(card_id, "../" + paths[card_id].relative_to(root).as_posix())
        return code(card_id)

    tiers = Counter(r["tier"] for r in ordered)
    categories = Counter(r["source_category"] for r in ordered)
    scale = f"当前登记 **{len(ordered)}** 张卡：" + " / ".join(f"{tier} {tiers[tier]}" for tier in ("Gold", "Silver", "Reference")) + "。"
    scale += "\n\n来源类别：" + " / ".join(f"`{category}` {count}" for category, count in sorted(categories.items())) + "。"

    output = {}
    output["master-index.md"] = page(
        "人物卡总索引",
        ["card_id", "人物", "来源档案", "tier", "原角色成年状态", "一级原型", "H4 成年现代角色（ADAPTATION）", "最近邻", "Anti-Clone"],
        [[code(r["card_id"]), person(r), link(r["source_work"], f"../sources/{r['card_id']}_sources.md"),
          cell(r["tier"]), code(r["adult_status"]), code(r["primary_archetype_id"]),
          cell(age(r) + " / " + (r.get("adult_adaptation_role") or "UNKNOWN")),
          neighbor(r), code(r.get("anti_clone_result"))] for r in ordered],
        scale + "\n\n等级与最近邻沿用现行卡片与摘要中的内部判断；本页不重新评定等级或执行语义反克隆审计。Reference 只进入总索引登记；应用视图仅列对应层已完成的 Gold / Silver。",
    )
    output["by-archetype.md"] = page(
        "按一级原型检索", ["一级原型", "人物", "tier", "一句话母体（R 摘要）"],
        [[code(r["primary_archetype_id"]) + "（" + cell(names[r["primary_archetype_id"]]) + "）",
          person(r), cell(r["tier"]), cell(capsule(r).get("one_line_archetype"))]
         for r in sorted(usable, key=lambda r: (r["primary_archetype_id"], r["card_id"]))],
        "原型归类为 INTERPRETATION。",
    )
    output["by-visual-hook.md"] = page(
        "按视觉钩子检索", ["人物", "tier", "H4 年龄 / 角色", "1—3 个记忆点", "第一眼误读", "剧情功能"],
        [[person(r), cell(r["tier"]), cell(age(r) + " / " + (r.get("adult_adaptation_role") or "UNKNOWN")),
          joined(r.get("adult_visual_signature") or []), cell(r.get("adult_low_register_first_glance")),
          joined(r.get("adult_visual_plot_functions") or [], "、")] for r in h4_records],
        "本页全部视觉设计属于 H4 / ADAPTATION，仅对声明的成年现代人物成立，不能解除原角色 V 的年龄门。",
    )
    output["by-identity.md"] = page(
        "按身份反差检索", ["人物", "tier", "来源作品", "H4 身份身体反差（ADAPTATION）", "原角色成年状态"],
        [[person(r), cell(r["tier"]), cell(r["source_work"]), joined(r.get("adult_identity_body_contrast") or []),
          code(r["adult_status"])] for r in h4_records],
        "“来源作品”只标识作品，不冒充原著身份；现代身份反差不能倒填为原著事实。",
    )
    output["by-desire-mechanism.md"] = page(
        "按欲望机制检索", ["人物", "tier", "长期匮乏", "第一次越界", "即时奖励", "加码逻辑", "最大误判"],
        [[person(r), cell(r["tier"])] + [cell(r.get(field)) for field in
                       ("long_term_lack", "first_crossing", "immediate_reward", "escalation_logic", "fatal_miscalculation")]
         for r in mechanisms], "机制字段属于 INTERPRETATION，须结合完整 M 层及反证使用。",
    )
    output["by-power-method.md"] = page(
        "按权力方式检索", ["人物", "tier", "权力方式", "最怕失去的资源", "一级原型"],
        [[person(r), cell(r["tier"]), cell(r.get("power_method")), cell(r.get("jealous_resource")),
          code(r["primary_archetype_id"])] for r in mechanisms], "权力与资源判断属于 INTERPRETATION。",
    )
    output["by-secret-method.md"] = page(
        "按秘密使用方式检索", ["人物", "tier", "秘密杠杆", "最近邻", "Anti-Clone"],
        [[person(r), cell(r["tier"]), cell(r.get("secret_leverage")), neighbor(r),
          code(r.get("anti_clone_result"))] for r in mechanisms], "秘密使用机制属于 INTERPRETATION；最近邻命中后回读 A 层差异。",
    )
    output["by-modern-role.md"] = page(
        "按现代角色检索", ["人物", "tier", "年龄", "现代角色", "阶层位置", "核心冲突", "公共 / 反差最强 / 危险场景衣着"],
        [[person(r), cell(r["tier"]), cell(age(r)), cell(r.get("adult_adaptation_role")),
          cell(container(r).get("class_position")), cell(container(r).get("core_conflict")),
          joined([(r.get("adult_clothing_contrast") or {}).get(key) or "UNKNOWN"
                  for key in ("public", "maximum", "danger")], " / ")] for r in h4_records],
        "本页现代容器与衣着全部属于 ADAPTATION，不是原著人物资料。",
    )
    output["by-relationship-mechanism.md"] = page(
        "按关系机制检索", ["人物", "tier", "一句话母体", "关系权力", "秘密使用", "最怕失去的资源"],
        [[person(r), cell(r["tier"]), cell(capsule(r).get("one_line_archetype")),
          cell(power(r).get("power_method")), cell(power(r).get("secret_use")),
          cell(power(r).get("feared_resource_loss"))] for r in capsules],
        "本页取自 R 快速调用胶囊，只用于召回；关系机制须回读 M / A 的依据与差异。",
    )
    output["by-plot-engine.md"] = page(
        "按剧情发动机检索", ["人物", "tier", "发动机 ID（回读 P）", "现代核心冲突（ADAPTATION）", "欲望链（R 摘要）"],
        [[person(r), cell(r["tier"]), "、".join(code(engine) for engine in r.get("plot_engine_ids") or []) or "UNKNOWN",
          cell(container(r).get("core_conflict")), cell(capsule(r).get("desire_chain"))] for r in engines],
        "机器摘要只含发动机 ID，没有各 P 发动机的完整触发、行动、阻力、收益、升级和代价。每张卡只列一行；实际发动机须回读该卡 P 层。",
    )
    return output


def stale_outputs(root, schema, records, outputs):
    stale = []
    for name, expected in outputs.items():
        path = root / "indexes" / name
        if not path.is_file() or read_utf8(path) != expected:
            stale.append("indexes/" + name)
    if schema.get("character_records") != character_cache(records):
        stale.append("data/archetypes.json:character_records")
    return stale


def replace_character_cache(path, records):
    """Replace just the cache array; leave schema content/format outside it intact."""
    raw = path.read_bytes().decode("utf-8")
    match = re.search(r'"character_records"\s*:\s*', raw)
    if not match:
        raise ValueError("archetypes.json must contain a character_records array")
    start = match.end()
    previous, consumed = json.JSONDecoder().raw_decode(raw[start:])
    expected = character_cache(records)
    if previous == expected:
        return False
    newline = "\r\n" if "\r\n" in raw else "\n"
    lines = json.dumps(expected, ensure_ascii=False, indent=2).splitlines()
    replacement = newline.join(line if i == 0 else "  " + line for i, line in enumerate(lines))
    path.write_bytes((raw[:start] + replacement + raw[start + consumed:]).encode("utf-8"))
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale/missing generated outputs without writing")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="Repository root (default: script location)")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        schema, records = load_library(root)
        outputs = generated_indexes(root, schema, records, card_files(root, records))
        stale = stale_outputs(root, schema, records, outputs)
        if args.check:
            for name in stale:
                print("STALE: " + name)
            if not stale:
                print(f"INDEX CHECK PASSED: {len(records)} records; {len(outputs)} indexes and character_records cache are current.")
            return 1 if stale else 0
        (root / "indexes").mkdir(exist_ok=True)
        changed = []
        for name, content in outputs.items():
            if "indexes/" + name in stale:
                (root / "indexes" / name).write_bytes(content.encode("utf-8"))
                changed.append("indexes/" + name)
        if replace_character_cache(root / "data/archetypes.json", records):
            changed.append("data/archetypes.json:character_records")
        print(f"INDEX BUILD PASSED: {len(records)} records; {len(changed)} outputs updated.")
        return 0
    except (OSError, UnicodeError, ValueError, KeyError, TypeError) as error:
        print(f"INDEX BUILD FAILED: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
